### PR TITLE
full and complite website clone of Newsweek.com

### PR DESCRIPTION
**Pull request by kirokoNjenga**
*What does this PR do?*
-Clone of Newsweek website
-Shows the ability to develop a responsive website with bootstrap framework
-Full test with w3validator and stylelint for CSS
-Had fun developing the project
***Please note***
-The reason why I have single commit by mistake I created a single branch and commit all my working there using vscode, the was no way to make a pull request I had to create a new repo

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
#### status: require changes🛑
# Hi @Samkiroko,
Impress first attempt🙂, the page looks amazing at **LG & SM**. Here are a few things we have to address to get this project approved.

**Footer**
* [ ] It contains Newsweek logo ([link to page](https://www.newsweek.com/))
* [ ] It contains social media icons ([link to page](https://www.newsweek.com/))
* [ ] It contains main navigation links ([link to page](https://www.newsweek.com/))
* [ ] **It changes with RWD breakpoints** ([link to page](https://www.newsweek.com/))

**@MD**

* [ ] Let us check the part after **LATEST NEWS** and compare it to the [newsweek page](newsweek.com)
#### original page👇
Screenshot from 2020-01-16 16-36-09
##### Your page‎👇
Screenshot from 2020-01-16 16-38-50
* [ ] Feature Slide show is missing and the part that comes immediately after it are missing, please add them
* [ ] Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)) Check line ```498, 513, 585``` on ```main.css```
### That is it, kindly make these changes and submit project for review
#### Happy coding
Addo Forison

**Comment by kirokoNjenga** [comment]
Added everything as required

**Review by mosesogwo — CHANGES_REQUESTED** [review]
### :clap:  Hello @Samkiroko, nice work but you didn't effect all the previously requested changes:
1. Social media icons are missing in the footer.

2. You did not effect this change from the previous review: 
image

3. Featured Slideshow and the sections after it are still missing.

4. Modify the font in the Editor's pick title to match the original.
image

**Kindly effect the changes and submit another code review request. Also note that your live link is not updated with the most recent changes.**

### Status: Changes requested.

**Comment by kirokoNjenga** [comment]
-Added all the requested changes

**Review by suretrust — APPROVED** [review]
Hi @Samkiroko, 👋 

### Great job, no deal-breaker. 🙌 Let's get this merged. 👍 

**Note:** Your commit messages could be better. `adding all required changes` is not a good commit message and I can see it repeated a number of times. What exactly did you add or remove, `Add missing social media icons` or `Add featured slideshow section` is a better commit message.

_Good luck with your future projects and happy coding!_ 🎉

**Pull request merged**
